import { ThemesType } from "./types";

export enum Colors {
    BLACK = '#000',
    WHITE = '#fff',
    TRANSPARENT_BLACK = 'rgba(0, 0, 0, 0.12)',
    TRANSPARENT_WHITE = 'rgba(255, 255, 255, 0.3)',
    CORIANDER = '#1c1919',
    COD_GRAY = '#131313',
    COD_GRAY_DARK = '#0c0b0b',
    COD_GRAY_MEDIUM = '#171717',
    COD_GRAY_LIGHT = '#1c1b1b',
    COD_GRAY_BROWN = '#1f1c1c',
    SPRING_LEAVES = '#5B8A72',
    SPRING_LEAVES_TRANSPARENT = '#56776c99',
    GREEN_TRANSPARENT = 'rgb(49 163 71 / 4%)',
    DARK_GREEN_TRANSPARENT = '#56776c21',
    GRAY_TRANSPARENT = '#9e9d9d0a',
    SOFT_PEACH = '#F5EDED',
    CABBAGE_PONT = '#464F41',
    MASALA = '#3E3636',
    BOTTLE_GREEN = '#0f4a34',
    ATHENS_GRAY = '#f3f4f6',
    DUSTY_GRAY = '#9e9d9d',
    TRANSPARENT = '#fff0',
    BOULDER = '#797979',
    SAN_MARINO = '#3f51b5',
    SAPPHIRE = '#27399b',
    SAPHIRE_TRANSPARENT = '#27399b59',
    PALE_GRAY_OPACITY= '#e5e5e58a'
}

export const Themes: ThemesType = {
    green: {
        body: Colors.WHITE,
        color: Colors.BLACK,
        subBarBackground: Colors.SPRING_LEAVES,
        addCategoryBtnBackground: Colors.CABBAGE_PONT,
        modalBackground: Colors.WHITE,
        buttonBackground: Colors.SPRING_LEAVES,
        buttonBackgroundHover: Colors.BOTTLE_GREEN,
        enteringModalBackground: Colors.COD_GRAY_LIGHT,
        statisticsBackground: Colors.ATHENS_GRAY,
        settingsBackground: Colors.ATHENS_GRAY,
        statisticsLineDayBackground: Colors.SPRING_LEAVES_TRANSPARENT,
        buttonGroupColor: Colors.BLACK,
        buttonActiveGroupColor: Colors.SPRING_LEAVES,
        buttonGroupHover: Colors.GREEN_TRANSPARENT,
        dataPikerIcon: Colors.COD_GRAY_LIGHT,
        inputBorder: Colors.DUSTY_GRAY,
        inputBorderHover: Colors.BLACK,
        inputBorderFocused: Colors.SPRING_LEAVES,
        labelFocused: Colors.SPRING_LEAVES,
        lineBackgroundHover: Colors.PALE_GRAY_OPACITY,
        buttonDisabledBackground: Colors.TRANSPARENT_BLACK,
        settingsOptionsTabActive: Colors.BLACK,
        datePikerLayout: Colors.WHITE,
        pickersDaySelected: Colors.SPRING_LEAVES,
        pickersDayHover: Colors.SPRING_LEAVES_TRANSPARENT,
        datePikerLayoutShadow: Colors.TRANSPARENT,
        selectHover: Colors.PALE_GRAY_OPACITY,
        selectSelected: Colors.TRANSPARENT_BLACK,
        showPasswordIconColor: Colors.BOULDER
    },
    dark: {
        body: Colors.COD_GRAY,
        color: Colors.WHITE,
        subBarBackground: Colors.COD_GRAY_DARK,
        addCategoryBtnBackground: Colors.SOFT_PEACH,
        modalBackground: Colors.COD_GRAY_MEDIUM,
        buttonBackground: Colors.SAN_MARINO,
        buttonBackgroundHover: Colors.SAPPHIRE,
        enteringModalBackground: Colors.COD_GRAY,
        statisticsBackground: Colors.COD_GRAY_DARK,
        settingsBackground: Colors.COD_GRAY_DARK,
        statisticsLineDayBackground: Colors.SOFT_PEACH,
        buttonGroupColor: Colors.WHITE,
        buttonActiveGroupColor: Colors.DUSTY_GRAY,
        buttonGroupHover: Colors.GRAY_TRANSPARENT,
        dataPikerIcon: Colors.ATHENS_GRAY,
        inputBorder: Colors.BOULDER,
        inputBorderHover: Colors.DUSTY_GRAY,
        inputBorderFocused: Colors.SAN_MARINO,
        labelFocused: Colors.SAN_MARINO,
        lineBackgroundHover: Colors.COD_GRAY_LIGHT,
        buttonDisabledBackground: Colors.DUSTY_GRAY,
        settingsOptionsTabActive: Colors.SOFT_PEACH,
        datePikerLayout: Colors.COD_GRAY_DARK,
        pickersDaySelected: Colors.SAPPHIRE,
        pickersDayHover: Colors.SAPHIRE_TRANSPARENT,
        datePikerLayoutShadow: Colors.TRANSPARENT_WHITE,
        selectHover: Colors.COD_GRAY_LIGHT,
        selectSelected: Colors.COD_GRAY_MEDIUM,
        showPasswordIconColor: Colors.DUSTY_GRAY
    }
}